In [5]:
!pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable


In [6]:
vector_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Одновимірний масив:", vector_1d)

Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10]


In [7]:
matrix_2d = np.zeros((3, 3))
print("\nДвовимірний масив з нулями:\n", matrix_2d)


Двовимірний масив з нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
random_matrix_int = np.random.randint(1, 11, (5, 5))
print("\nМасив розміром 5x5 з випадковими цілими числами:\n", random_matrix_int)


Масив розміром 5x5 з випадковими цілими числами:
 [[8 9 6 6 6]
 [1 9 6 4 9]
 [5 9 3 5 4]
 [1 6 4 2 4]
 [2 4 7 2 2]]


In [9]:
random_matrix_float = np.random.rand(4, 4)
print("\nМасив розміром 4x4 з випадковими дійсними числами:\n", random_matrix_float)


Масив розміром 4x4 з випадковими дійсними числами:
 [[0.22241512 0.05134197 0.58936567 0.13570403]
 [0.93263078 0.69371223 0.84882393 0.1748114 ]
 [0.39662051 0.76493231 0.81481838 0.81827856]
 [0.30949081 0.57691713 0.08530037 0.69372765]]


In [10]:
vector_a = np.random.randint(1, 11, 5)
vector_b = np.random.randint(1, 11, 5)
print("\nВектор A:", vector_a)
print("Вектор B:", vector_b)


Вектор A: [ 6  1  8 10  1]
Вектор B: [5 6 6 5 7]


In [11]:
print("\nДодавання:", vector_a + vector_b)
print("Віднімання:", vector_a - vector_b)
print("Множення:", vector_a * vector_b)


Додавання: [11  7 14 15  8]
Віднімання: [ 1 -5  2  5 -6]
Множення: [30  6 48 50  7]


In [12]:
vector_1 = np.random.randint(1, 11, 7)
vector_2 = np.random.randint(1, 11, 7)
print("\nВектор 1:", vector_1)
print("Вектор 2:", vector_2)


Вектор 1: [10  7  1  2  5  8  3]
Вектор 2: [1 3 3 8 8 5 9]


In [13]:
scalar_product = np.dot(vector_1, vector_2)
print("\nСкалярний добуток:", scalar_product)



Скалярний добуток: 157


In [14]:
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))
print("\nМатриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)


Матриця 2x2:
 [[8 9]
 [3 2]]
Матриця 2x3:
 [[8 4 3]
 [4 5 8]]


In [15]:
result_matrix = np.dot(matrix_2x2, matrix_2x3)
print("\nРезультат перемноження:\n", result_matrix)


Результат перемноження:
 [[100  77  96]
 [ 32  22  25]]


In [16]:
matrix_3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("\nОбернена матриця:\n", inverse_matrix)


Обернена матриця:
 [[-0.26896552  0.48965517 -0.51724138]
 [ 0.31724138 -0.37241379  0.37931034]
 [ 0.02758621 -0.07586207  0.20689655]]


In [17]:
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = matrix_4x4.T
print("\nТранспонована матриця 4x4:\n", transposed_matrix)



Транспонована матриця 4x4:
 [[0.14906295 0.64582273 0.58664777 0.94652119]
 [0.18934447 0.91705557 0.11141357 0.87430833]
 [0.48565251 0.96033771 0.75061609 0.14972919]
 [0.42130968 0.86124322 0.12935692 0.4345739 ]]


In [18]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)
result_vector = np.dot(matrix_3x4, vector_4)
print("\nРезультат перемноження матриці на вектор:\n", result_vector)


Результат перемноження матриці на вектор:
 [174 120 105]


In [19]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
result_vector_2 = np.dot(matrix_2x3, vector_3)
print("\nРезультат перемноження матриці на вектор:\n", result_vector_2)


Результат перемноження матриці на вектор:
 [0.48802801 0.57787934]


In [20]:
matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 2))
elementwise_product = matrix_a * matrix_b
print("\nПоелементне множення:\n", elementwise_product)


Поелементне множення:
 [[32 56]
 [60 36]]


In [21]:
matrix_product = np.dot(matrix_a, matrix_b)
print("\nДобуток матриць:\n", matrix_product)


Добуток матриць:
 [[102 106]
 [ 84  84]]


In [22]:
matrix_5x5 = np.random.randint(1, 101, (5, 5))
sum_elements = np.sum(matrix_5x5)
print("\nСума елементів матриці 5x5:", sum_elements)


Сума елементів матриці 5x5: 1310


In [23]:
matrix_4x4_a = np.random.randint(1, 11, (4, 4))
matrix_4x4_b = np.random.randint(1, 11, (4, 4))
difference_matrix = matrix_4x4_a - matrix_4x4_b
print("\nРізниця матриць:\n", difference_matrix)



Різниця матриць:
 [[ 6  4  1  2]
 [-1  3  4 -4]
 [ 7 -2  5 -1]
 [ 0 -2  1 -2]]


In [24]:
matrix_3x3 = np.random.randint(1, 11, (3, 3))
row_sums = np.sum(matrix_3x3, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("\nВектор-стовпчик з сумами елементів кожного рядка:\n", column_vector)


Вектор-стовпчик з сумами елементів кожного рядка:
 [[21]
 [19]
 [29]]


In [25]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
squared_matrix = matrix_3x4 ** 2
print("\nМатриця з квадратами чисел:\n", squared_matrix)


Матриця з квадратами чисел:
 [[ 16   1  36  49]
 [ 16  25 100  64]
 [ 49  81  81  25]]


In [26]:
vector_4 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector_4)
print("\nВектор з квадратними коренями чисел:\n", sqrt_vector)


Вектор з квадратними коренями чисел:
 [5.47722558 6.32455532 6.55743852 5.38516481]
